// <auto-generated />
using DA2_2018_LabCompras_tlevi29.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DA2_2018_LabCompras_tlevi29.Migrations
{
    [DbContext(typeof(LabComprasDbContext))]
    partial class LabComprasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DA2_2018_LabCompras_tlevi29.Models.Conta", b =>
                {
                    b.Property<int>("ContaID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativa");

                    b.Property<string>("NomeTitular")
                        .IsRequired();

                    b.Property<int?>("Saldo")
                        .IsRequired();

                    b.HasKey("ContaID");

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("DA2_2018_LabCompras_tlevi29.Models.Despesa", b =>
                {
                    b.Property<int>("DespesaID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Categoria")
                        .IsRequired();

                    b.Property<string>("NomeDespesa")
                        .IsRequired();

                    b.Property<bool>("Pago");

                    b.Property<int>("Quantidade");

                    b.Property<double?>("Valor")
                        .IsRequired();

                    b.HasKey("DespesaID");

                    b.ToTable("Despesas");
                });
#pragma warning restore 612, 618
        }
    }
}
